name: hrplatform
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1

  image_picker: ^1.1.2
  dio: ^5.5.0+1
  device_info_plus: ^11.1.1
  unique_identifier: ^0.3.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  rename: ^3.0.2
  keyboard_dismisser: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  pull_to_refresh: ^2.0.0
  stylish_bottom_bar: ^1.1.0
  lottie: ^3.1.2
  getwidget: ^4.0.0
  photo_view: ^0.15.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  internet_connection_checker: ^1.0.0+1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - env/
    - assets/images/
    - assets/icons/
    - assets/flag/
    - assets/animation/


  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSansLaoUI-Regular.ttf

